// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pkg/agentpb/v1/agent.proto

package agentpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_AddUserRule_FullMethodName       = "/agent.v1.AgentService/AddUserRule"
	AgentService_RemoveUserRule_FullMethodName    = "/agent.v1.AgentService/RemoveUserRule"
	AgentService_ListUserRules_FullMethodName     = "/agent.v1.AgentService/ListUserRules"
	AgentService_EnableUserRule_FullMethodName    = "/agent.v1.AgentService/EnableUserRule"
	AgentService_DisableUserRule_FullMethodName   = "/agent.v1.AgentService/DisableUserRule"
	AgentService_AddMachineRule_FullMethodName    = "/agent.v1.AgentService/AddMachineRule"
	AgentService_RemoveMachineRule_FullMethodName = "/agent.v1.AgentService/RemoveMachineRule"
	AgentService_ListMachineRules_FullMethodName  = "/agent.v1.AgentService/ListMachineRules"
	AgentService_TriggerSync_FullMethodName       = "/agent.v1.AgentService/TriggerSync"
	AgentService_GetSyncStatus_FullMethodName     = "/agent.v1.AgentService/GetSyncStatus"
	AgentService_RequestRestore_FullMethodName    = "/agent.v1.AgentService/RequestRestore"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	AddUserRule(ctx context.Context, in *AddUserRuleRequest, opts ...grpc.CallOption) (*AddUserRuleResponse, error)
	RemoveUserRule(ctx context.Context, in *RemoveUserRuleRequest, opts ...grpc.CallOption) (*RemoveUserRuleResponse, error)
	ListUserRules(ctx context.Context, in *ListUserRulesRequest, opts ...grpc.CallOption) (*ListUserRulesResponse, error)
	EnableUserRule(ctx context.Context, in *EnableUserRuleRequest, opts ...grpc.CallOption) (*EnableUserRuleResponse, error)
	DisableUserRule(ctx context.Context, in *DisableUserRuleRequest, opts ...grpc.CallOption) (*DisableUserRuleResponse, error)
	AddMachineRule(ctx context.Context, in *AddMachineRuleRequest, opts ...grpc.CallOption) (*AddMachineRuleResponse, error)
	RemoveMachineRule(ctx context.Context, in *RemoveMachineRuleRequest, opts ...grpc.CallOption) (*RemoveMachineRuleResponse, error)
	ListMachineRules(ctx context.Context, in *ListMachineRulesRequest, opts ...grpc.CallOption) (*ListMachineRulesResponse, error)
	TriggerSync(ctx context.Context, in *TriggerSyncRequest, opts ...grpc.CallOption) (*TriggerSyncResponse, error)
	GetSyncStatus(ctx context.Context, in *GetSyncStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncStatusUpdate], error)
	RequestRestore(ctx context.Context, in *RequestRestoreRequest, opts ...grpc.CallOption) (*RequestRestoreResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) AddUserRule(ctx context.Context, in *AddUserRuleRequest, opts ...grpc.CallOption) (*AddUserRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_AddUserRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RemoveUserRule(ctx context.Context, in *RemoveUserRuleRequest, opts ...grpc.CallOption) (*RemoveUserRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_RemoveUserRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListUserRules(ctx context.Context, in *ListUserRulesRequest, opts ...grpc.CallOption) (*ListUserRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserRulesResponse)
	err := c.cc.Invoke(ctx, AgentService_ListUserRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) EnableUserRule(ctx context.Context, in *EnableUserRuleRequest, opts ...grpc.CallOption) (*EnableUserRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableUserRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_EnableUserRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DisableUserRule(ctx context.Context, in *DisableUserRuleRequest, opts ...grpc.CallOption) (*DisableUserRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableUserRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_DisableUserRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AddMachineRule(ctx context.Context, in *AddMachineRuleRequest, opts ...grpc.CallOption) (*AddMachineRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMachineRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_AddMachineRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RemoveMachineRule(ctx context.Context, in *RemoveMachineRuleRequest, opts ...grpc.CallOption) (*RemoveMachineRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMachineRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_RemoveMachineRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListMachineRules(ctx context.Context, in *ListMachineRulesRequest, opts ...grpc.CallOption) (*ListMachineRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMachineRulesResponse)
	err := c.cc.Invoke(ctx, AgentService_ListMachineRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TriggerSync(ctx context.Context, in *TriggerSyncRequest, opts ...grpc.CallOption) (*TriggerSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerSyncResponse)
	err := c.cc.Invoke(ctx, AgentService_TriggerSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSyncStatus(ctx context.Context, in *GetSyncStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_GetSyncStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSyncStatusRequest, SyncStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetSyncStatusClient = grpc.ServerStreamingClient[SyncStatusUpdate]

func (c *agentServiceClient) RequestRestore(ctx context.Context, in *RequestRestoreRequest, opts ...grpc.CallOption) (*RequestRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestRestoreResponse)
	err := c.cc.Invoke(ctx, AgentService_RequestRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	AddUserRule(context.Context, *AddUserRuleRequest) (*AddUserRuleResponse, error)
	RemoveUserRule(context.Context, *RemoveUserRuleRequest) (*RemoveUserRuleResponse, error)
	ListUserRules(context.Context, *ListUserRulesRequest) (*ListUserRulesResponse, error)
	EnableUserRule(context.Context, *EnableUserRuleRequest) (*EnableUserRuleResponse, error)
	DisableUserRule(context.Context, *DisableUserRuleRequest) (*DisableUserRuleResponse, error)
	AddMachineRule(context.Context, *AddMachineRuleRequest) (*AddMachineRuleResponse, error)
	RemoveMachineRule(context.Context, *RemoveMachineRuleRequest) (*RemoveMachineRuleResponse, error)
	ListMachineRules(context.Context, *ListMachineRulesRequest) (*ListMachineRulesResponse, error)
	TriggerSync(context.Context, *TriggerSyncRequest) (*TriggerSyncResponse, error)
	GetSyncStatus(*GetSyncStatusRequest, grpc.ServerStreamingServer[SyncStatusUpdate]) error
	RequestRestore(context.Context, *RequestRestoreRequest) (*RequestRestoreResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) AddUserRule(context.Context, *AddUserRuleRequest) (*AddUserRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserRule not implemented")
}
func (UnimplementedAgentServiceServer) RemoveUserRule(context.Context, *RemoveUserRuleRequest) (*RemoveUserRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserRule not implemented")
}
func (UnimplementedAgentServiceServer) ListUserRules(context.Context, *ListUserRulesRequest) (*ListUserRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserRules not implemented")
}
func (UnimplementedAgentServiceServer) EnableUserRule(context.Context, *EnableUserRuleRequest) (*EnableUserRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableUserRule not implemented")
}
func (UnimplementedAgentServiceServer) DisableUserRule(context.Context, *DisableUserRuleRequest) (*DisableUserRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableUserRule not implemented")
}
func (UnimplementedAgentServiceServer) AddMachineRule(context.Context, *AddMachineRuleRequest) (*AddMachineRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMachineRule not implemented")
}
func (UnimplementedAgentServiceServer) RemoveMachineRule(context.Context, *RemoveMachineRuleRequest) (*RemoveMachineRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMachineRule not implemented")
}
func (UnimplementedAgentServiceServer) ListMachineRules(context.Context, *ListMachineRulesRequest) (*ListMachineRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMachineRules not implemented")
}
func (UnimplementedAgentServiceServer) TriggerSync(context.Context, *TriggerSyncRequest) (*TriggerSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSync not implemented")
}
func (UnimplementedAgentServiceServer) GetSyncStatus(*GetSyncStatusRequest, grpc.ServerStreamingServer[SyncStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method GetSyncStatus not implemented")
}
func (UnimplementedAgentServiceServer) RequestRestore(context.Context, *RequestRestoreRequest) (*RequestRestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestRestore not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_AddUserRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddUserRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AddUserRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddUserRule(ctx, req.(*AddUserRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RemoveUserRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RemoveUserRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RemoveUserRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RemoveUserRule(ctx, req.(*RemoveUserRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListUserRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListUserRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListUserRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListUserRules(ctx, req.(*ListUserRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_EnableUserRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableUserRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).EnableUserRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_EnableUserRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).EnableUserRule(ctx, req.(*EnableUserRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DisableUserRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableUserRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DisableUserRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DisableUserRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DisableUserRule(ctx, req.(*DisableUserRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AddMachineRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMachineRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddMachineRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AddMachineRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddMachineRule(ctx, req.(*AddMachineRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RemoveMachineRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMachineRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RemoveMachineRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RemoveMachineRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RemoveMachineRule(ctx, req.(*RemoveMachineRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListMachineRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMachineRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListMachineRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListMachineRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListMachineRules(ctx, req.(*ListMachineRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_TriggerSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).TriggerSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_TriggerSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).TriggerSync(ctx, req.(*TriggerSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSyncStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSyncStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GetSyncStatus(m, &grpc.GenericServerStream[GetSyncStatusRequest, SyncStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetSyncStatusServer = grpc.ServerStreamingServer[SyncStatusUpdate]

func _AgentService_RequestRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RequestRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RequestRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RequestRestore(ctx, req.(*RequestRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUserRule",
			Handler:    _AgentService_AddUserRule_Handler,
		},
		{
			MethodName: "RemoveUserRule",
			Handler:    _AgentService_RemoveUserRule_Handler,
		},
		{
			MethodName: "ListUserRules",
			Handler:    _AgentService_ListUserRules_Handler,
		},
		{
			MethodName: "EnableUserRule",
			Handler:    _AgentService_EnableUserRule_Handler,
		},
		{
			MethodName: "DisableUserRule",
			Handler:    _AgentService_DisableUserRule_Handler,
		},
		{
			MethodName: "AddMachineRule",
			Handler:    _AgentService_AddMachineRule_Handler,
		},
		{
			MethodName: "RemoveMachineRule",
			Handler:    _AgentService_RemoveMachineRule_Handler,
		},
		{
			MethodName: "ListMachineRules",
			Handler:    _AgentService_ListMachineRules_Handler,
		},
		{
			MethodName: "TriggerSync",
			Handler:    _AgentService_TriggerSync_Handler,
		},
		{
			MethodName: "RequestRestore",
			Handler:    _AgentService_RequestRestore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSyncStatus",
			Handler:       _AgentService_GetSyncStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/agentpb/v1/agent.proto",
}
