// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Rule) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AddUserRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRuleRequest) Reset() {
	*x = AddUserRuleRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRuleRequest) ProtoMessage() {}

func (x *AddUserRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRuleRequest.ProtoReflect.Descriptor instead.
func (*AddUserRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddUserRuleRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *AddUserRuleRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type AddUserRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRuleResponse) Reset() {
	*x = AddUserRuleResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRuleResponse) ProtoMessage() {}

func (x *AddUserRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRuleResponse.ProtoReflect.Descriptor instead.
func (*AddUserRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

type RemoveUserRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRuleRequest) Reset() {
	*x = RemoveUserRuleRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRuleRequest) ProtoMessage() {}

func (x *RemoveUserRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveUserRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveUserRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRuleResponse) Reset() {
	*x = RemoveUserRuleResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRuleResponse) ProtoMessage() {}

func (x *RemoveUserRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRuleResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

type ListUserRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRulesRequest) Reset() {
	*x = ListUserRulesRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRulesRequest) ProtoMessage() {}

func (x *ListUserRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRulesRequest.ProtoReflect.Descriptor instead.
func (*ListUserRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

type ListUserRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRulesResponse) Reset() {
	*x = ListUserRulesResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRulesResponse) ProtoMessage() {}

func (x *ListUserRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRulesResponse.ProtoReflect.Descriptor instead.
func (*ListUserRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type EnableUserRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableUserRuleRequest) Reset() {
	*x = EnableUserRuleRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableUserRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableUserRuleRequest) ProtoMessage() {}

func (x *EnableUserRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableUserRuleRequest.ProtoReflect.Descriptor instead.
func (*EnableUserRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *EnableUserRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnableUserRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableUserRuleResponse) Reset() {
	*x = EnableUserRuleResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableUserRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableUserRuleResponse) ProtoMessage() {}

func (x *EnableUserRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableUserRuleResponse.ProtoReflect.Descriptor instead.
func (*EnableUserRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

type DisableUserRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableUserRuleRequest) Reset() {
	*x = DisableUserRuleRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableUserRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableUserRuleRequest) ProtoMessage() {}

func (x *DisableUserRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableUserRuleRequest.ProtoReflect.Descriptor instead.
func (*DisableUserRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DisableUserRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DisableUserRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableUserRuleResponse) Reset() {
	*x = DisableUserRuleResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableUserRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableUserRuleResponse) ProtoMessage() {}

func (x *DisableUserRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableUserRuleResponse.ProtoReflect.Descriptor instead.
func (*DisableUserRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

type AddMachineRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Schedule      string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Exclude       []string               `protobuf:"bytes,4,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMachineRuleRequest) Reset() {
	*x = AddMachineRuleRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMachineRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMachineRuleRequest) ProtoMessage() {}

func (x *AddMachineRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMachineRuleRequest.ProtoReflect.Descriptor instead.
func (*AddMachineRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AddMachineRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMachineRuleRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *AddMachineRuleRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *AddMachineRuleRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type AddMachineRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMachineRuleResponse) Reset() {
	*x = AddMachineRuleResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMachineRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMachineRuleResponse) ProtoMessage() {}

func (x *AddMachineRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMachineRuleResponse.ProtoReflect.Descriptor instead.
func (*AddMachineRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

type RemoveMachineRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMachineRuleRequest) Reset() {
	*x = RemoveMachineRuleRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMachineRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMachineRuleRequest) ProtoMessage() {}

func (x *RemoveMachineRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMachineRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveMachineRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMachineRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveMachineRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMachineRuleResponse) Reset() {
	*x = RemoveMachineRuleResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMachineRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMachineRuleResponse) ProtoMessage() {}

func (x *RemoveMachineRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMachineRuleResponse.ProtoReflect.Descriptor instead.
func (*RemoveMachineRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

type ListMachineRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineRulesRequest) Reset() {
	*x = ListMachineRulesRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineRulesRequest) ProtoMessage() {}

func (x *ListMachineRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineRulesRequest.ProtoReflect.Descriptor instead.
func (*ListMachineRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

type ListMachineRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineRulesResponse) Reset() {
	*x = ListMachineRulesResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineRulesResponse) ProtoMessage() {}

func (x *ListMachineRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineRulesResponse.ProtoReflect.Descriptor instead.
func (*ListMachineRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ListMachineRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type TriggerSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleName      string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"` // empty = all rules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSyncRequest) Reset() {
	*x = TriggerSyncRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSyncRequest) ProtoMessage() {}

func (x *TriggerSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSyncRequest.ProtoReflect.Descriptor instead.
func (*TriggerSyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *TriggerSyncRequest) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

type TriggerSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSyncResponse) Reset() {
	*x = TriggerSyncResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSyncResponse) ProtoMessage() {}

func (x *TriggerSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSyncResponse.ProtoReflect.Descriptor instead.
func (*TriggerSyncResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *TriggerSyncResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetSyncStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // empty = latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncStatusRequest) Reset() {
	*x = GetSyncStatusRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusRequest) ProtoMessage() {}

func (x *GetSyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetSyncStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type SyncStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"` // SCANNING, TRANSFERRING, COMPLETED, FAILED
	Stats         *SyncStats             `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	CurrentFiles  []string               `protobuf:"bytes,6,rep,name=current_files,json=currentFiles,proto3" json:"current_files,omitempty"` // files in current batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatusUpdate) Reset() {
	*x = SyncStatusUpdate{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusUpdate) ProtoMessage() {}

func (x *SyncStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusUpdate.ProtoReflect.Descriptor instead.
func (*SyncStatusUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *SyncStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SyncStatusUpdate) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SyncStatusUpdate) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SyncStatusUpdate) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SyncStatusUpdate) GetStats() *SyncStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *SyncStatusUpdate) GetCurrentFiles() []string {
	if x != nil {
		return x.CurrentFiles
	}
	return nil
}

type SyncStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalFiles       int64                  `protobuf:"varint,1,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	ScannedFiles     int64                  `protobuf:"varint,2,opt,name=scanned_files,json=scannedFiles,proto3" json:"scanned_files,omitempty"`
	ChangedFiles     int64                  `protobuf:"varint,3,opt,name=changed_files,json=changedFiles,proto3" json:"changed_files,omitempty"`
	TransferredFiles int64                  `protobuf:"varint,4,opt,name=transferred_files,json=transferredFiles,proto3" json:"transferred_files,omitempty"`
	TransferredBytes int64                  `protobuf:"varint,5,opt,name=transferred_bytes,json=transferredBytes,proto3" json:"transferred_bytes,omitempty"`
	CurrentRateBps   int64                  `protobuf:"varint,6,opt,name=current_rate_bps,json=currentRateBps,proto3" json:"current_rate_bps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncStats) Reset() {
	*x = SyncStats{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStats) ProtoMessage() {}

func (x *SyncStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStats.ProtoReflect.Descriptor instead.
func (*SyncStats) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *SyncStats) GetTotalFiles() int64 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *SyncStats) GetScannedFiles() int64 {
	if x != nil {
		return x.ScannedFiles
	}
	return 0
}

func (x *SyncStats) GetChangedFiles() int64 {
	if x != nil {
		return x.ChangedFiles
	}
	return 0
}

func (x *SyncStats) GetTransferredFiles() int64 {
	if x != nil {
		return x.TransferredFiles
	}
	return 0
}

func (x *SyncStats) GetTransferredBytes() int64 {
	if x != nil {
		return x.TransferredBytes
	}
	return 0
}

func (x *SyncStats) GetCurrentRateBps() int64 {
	if x != nil {
		return x.CurrentRateBps
	}
	return 0
}

type RequestRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPath    string                 `protobuf:"bytes,1,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"` // empty = ~/restored/
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRestoreRequest) Reset() {
	*x = RequestRestoreRequest{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRestoreRequest) ProtoMessage() {}

func (x *RequestRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRestoreRequest.ProtoReflect.Descriptor instead.
func (*RequestRestoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *RequestRestoreRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type RequestRestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRestoreResponse) Reset() {
	*x = RequestRestoreResponse{}
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRestoreResponse) ProtoMessage() {}

func (x *RequestRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRestoreResponse.ProtoReflect.Descriptor instead.
func (*RequestRestoreResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *RequestRestoreResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_api_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/agent/v1/agent.proto\x12\bagent.v1\"d\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"X\n" +
	"\x12AddUserRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\"\x15\n" +
	"\x13AddUserRuleResponse\"+\n" +
	"\x15RemoveUserRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16RemoveUserRuleResponse\"\x16\n" +
	"\x14ListUserRulesRequest\"=\n" +
	"\x15ListUserRulesResponse\x12$\n" +
	"\x05rules\x18\x01 \x03(\v2\x0e.agent.v1.RuleR\x05rules\"+\n" +
	"\x15EnableUserRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16EnableUserRuleResponse\",\n" +
	"\x16DisableUserRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17DisableUserRuleResponse\"w\n" +
	"\x15AddMachineRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x18\n" +
	"\aexclude\x18\x04 \x03(\tR\aexclude\"\x18\n" +
	"\x16AddMachineRuleResponse\".\n" +
	"\x18RemoveMachineRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1b\n" +
	"\x19RemoveMachineRuleResponse\"\x19\n" +
	"\x17ListMachineRulesRequest\"@\n" +
	"\x18ListMachineRulesResponse\x12$\n" +
	"\x05rules\x18\x01 \x03(\v2\x0e.agent.v1.RuleR\x05rules\"1\n" +
	"\x12TriggerSyncRequest\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\".\n" +
	"\x13TriggerSyncResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"/\n" +
	"\x14GetSyncStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc5\x01\n" +
	"\x10SyncStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12)\n" +
	"\x05stats\x18\x05 \x01(\v2\x13.agent.v1.SyncStatsR\x05stats\x12#\n" +
	"\rcurrent_files\x18\x06 \x03(\tR\fcurrentFiles\"\xfa\x01\n" +
	"\tSyncStats\x12\x1f\n" +
	"\vtotal_files\x18\x01 \x01(\x03R\n" +
	"totalFiles\x12#\n" +
	"\rscanned_files\x18\x02 \x01(\x03R\fscannedFiles\x12#\n" +
	"\rchanged_files\x18\x03 \x01(\x03R\fchangedFiles\x12+\n" +
	"\x11transferred_files\x18\x04 \x01(\x03R\x10transferredFiles\x12+\n" +
	"\x11transferred_bytes\x18\x05 \x01(\x03R\x10transferredBytes\x12(\n" +
	"\x10current_rate_bps\x18\x06 \x01(\x03R\x0ecurrentRateBps\"8\n" +
	"\x15RequestRestoreRequest\x12\x1f\n" +
	"\vtarget_path\x18\x01 \x01(\tR\n" +
	"targetPath\"1\n" +
	"\x16RequestRestoreResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId2\xac\a\n" +
	"\fAgentService\x12J\n" +
	"\vAddUserRule\x12\x1c.agent.v1.AddUserRuleRequest\x1a\x1d.agent.v1.AddUserRuleResponse\x12S\n" +
	"\x0eRemoveUserRule\x12\x1f.agent.v1.RemoveUserRuleRequest\x1a .agent.v1.RemoveUserRuleResponse\x12P\n" +
	"\rListUserRules\x12\x1e.agent.v1.ListUserRulesRequest\x1a\x1f.agent.v1.ListUserRulesResponse\x12S\n" +
	"\x0eEnableUserRule\x12\x1f.agent.v1.EnableUserRuleRequest\x1a .agent.v1.EnableUserRuleResponse\x12V\n" +
	"\x0fDisableUserRule\x12 .agent.v1.DisableUserRuleRequest\x1a!.agent.v1.DisableUserRuleResponse\x12S\n" +
	"\x0eAddMachineRule\x12\x1f.agent.v1.AddMachineRuleRequest\x1a .agent.v1.AddMachineRuleResponse\x12\\\n" +
	"\x11RemoveMachineRule\x12\".agent.v1.RemoveMachineRuleRequest\x1a#.agent.v1.RemoveMachineRuleResponse\x12Y\n" +
	"\x10ListMachineRules\x12!.agent.v1.ListMachineRulesRequest\x1a\".agent.v1.ListMachineRulesResponse\x12J\n" +
	"\vTriggerSync\x12\x1c.agent.v1.TriggerSyncRequest\x1a\x1d.agent.v1.TriggerSyncResponse\x12M\n" +
	"\rGetSyncStatus\x12\x1e.agent.v1.GetSyncStatusRequest\x1a\x1a.agent.v1.SyncStatusUpdate0\x01\x12S\n" +
	"\x0eRequestRestore\x12\x1f.agent.v1.RequestRestoreRequest\x1a .agent.v1.RequestRestoreResponseB\x98\x01\n" +
	"\fcom.agent.v1B\n" +
	"AgentProtoP\x01Z;github.com/example/datavault/pkg/api/proto/agent/v1;agentv1\xa2\x02\x03AXX\xaa\x02\bAgent.V1\xca\x02\bAgent\\V1\xe2\x02\x14Agent\\V1\\GPBMetadata\xea\x02\tAgent::V1b\x06proto3"

var (
	file_api_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_api_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_v1_agent_proto_rawDesc), len(file_api_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_v1_agent_proto_rawDescData
}

var file_api_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_agent_v1_agent_proto_goTypes = []any{
	(*Rule)(nil),                      // 0: agent.v1.Rule
	(*AddUserRuleRequest)(nil),        // 1: agent.v1.AddUserRuleRequest
	(*AddUserRuleResponse)(nil),       // 2: agent.v1.AddUserRuleResponse
	(*RemoveUserRuleRequest)(nil),     // 3: agent.v1.RemoveUserRuleRequest
	(*RemoveUserRuleResponse)(nil),    // 4: agent.v1.RemoveUserRuleResponse
	(*ListUserRulesRequest)(nil),      // 5: agent.v1.ListUserRulesRequest
	(*ListUserRulesResponse)(nil),     // 6: agent.v1.ListUserRulesResponse
	(*EnableUserRuleRequest)(nil),     // 7: agent.v1.EnableUserRuleRequest
	(*EnableUserRuleResponse)(nil),    // 8: agent.v1.EnableUserRuleResponse
	(*DisableUserRuleRequest)(nil),    // 9: agent.v1.DisableUserRuleRequest
	(*DisableUserRuleResponse)(nil),   // 10: agent.v1.DisableUserRuleResponse
	(*AddMachineRuleRequest)(nil),     // 11: agent.v1.AddMachineRuleRequest
	(*AddMachineRuleResponse)(nil),    // 12: agent.v1.AddMachineRuleResponse
	(*RemoveMachineRuleRequest)(nil),  // 13: agent.v1.RemoveMachineRuleRequest
	(*RemoveMachineRuleResponse)(nil), // 14: agent.v1.RemoveMachineRuleResponse
	(*ListMachineRulesRequest)(nil),   // 15: agent.v1.ListMachineRulesRequest
	(*ListMachineRulesResponse)(nil),  // 16: agent.v1.ListMachineRulesResponse
	(*TriggerSyncRequest)(nil),        // 17: agent.v1.TriggerSyncRequest
	(*TriggerSyncResponse)(nil),       // 18: agent.v1.TriggerSyncResponse
	(*GetSyncStatusRequest)(nil),      // 19: agent.v1.GetSyncStatusRequest
	(*SyncStatusUpdate)(nil),          // 20: agent.v1.SyncStatusUpdate
	(*SyncStats)(nil),                 // 21: agent.v1.SyncStats
	(*RequestRestoreRequest)(nil),     // 22: agent.v1.RequestRestoreRequest
	(*RequestRestoreResponse)(nil),    // 23: agent.v1.RequestRestoreResponse
}
var file_api_proto_agent_v1_agent_proto_depIdxs = []int32{
	0,  // 0: agent.v1.ListUserRulesResponse.rules:type_name -> agent.v1.Rule
	0,  // 1: agent.v1.ListMachineRulesResponse.rules:type_name -> agent.v1.Rule
	21, // 2: agent.v1.SyncStatusUpdate.stats:type_name -> agent.v1.SyncStats
	1,  // 3: agent.v1.AgentService.AddUserRule:input_type -> agent.v1.AddUserRuleRequest
	3,  // 4: agent.v1.AgentService.RemoveUserRule:input_type -> agent.v1.RemoveUserRuleRequest
	5,  // 5: agent.v1.AgentService.ListUserRules:input_type -> agent.v1.ListUserRulesRequest
	7,  // 6: agent.v1.AgentService.EnableUserRule:input_type -> agent.v1.EnableUserRuleRequest
	9,  // 7: agent.v1.AgentService.DisableUserRule:input_type -> agent.v1.DisableUserRuleRequest
	11, // 8: agent.v1.AgentService.AddMachineRule:input_type -> agent.v1.AddMachineRuleRequest
	13, // 9: agent.v1.AgentService.RemoveMachineRule:input_type -> agent.v1.RemoveMachineRuleRequest
	15, // 10: agent.v1.AgentService.ListMachineRules:input_type -> agent.v1.ListMachineRulesRequest
	17, // 11: agent.v1.AgentService.TriggerSync:input_type -> agent.v1.TriggerSyncRequest
	19, // 12: agent.v1.AgentService.GetSyncStatus:input_type -> agent.v1.GetSyncStatusRequest
	22, // 13: agent.v1.AgentService.RequestRestore:input_type -> agent.v1.RequestRestoreRequest
	2,  // 14: agent.v1.AgentService.AddUserRule:output_type -> agent.v1.AddUserRuleResponse
	4,  // 15: agent.v1.AgentService.RemoveUserRule:output_type -> agent.v1.RemoveUserRuleResponse
	6,  // 16: agent.v1.AgentService.ListUserRules:output_type -> agent.v1.ListUserRulesResponse
	8,  // 17: agent.v1.AgentService.EnableUserRule:output_type -> agent.v1.EnableUserRuleResponse
	10, // 18: agent.v1.AgentService.DisableUserRule:output_type -> agent.v1.DisableUserRuleResponse
	12, // 19: agent.v1.AgentService.AddMachineRule:output_type -> agent.v1.AddMachineRuleResponse
	14, // 20: agent.v1.AgentService.RemoveMachineRule:output_type -> agent.v1.RemoveMachineRuleResponse
	16, // 21: agent.v1.AgentService.ListMachineRules:output_type -> agent.v1.ListMachineRulesResponse
	18, // 22: agent.v1.AgentService.TriggerSync:output_type -> agent.v1.TriggerSyncResponse
	20, // 23: agent.v1.AgentService.GetSyncStatus:output_type -> agent.v1.SyncStatusUpdate
	23, // 24: agent.v1.AgentService.RequestRestore:output_type -> agent.v1.RequestRestoreResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_agent_v1_agent_proto_init() }
func file_api_proto_agent_v1_agent_proto_init() {
	if File_api_proto_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_v1_agent_proto_rawDesc), len(file_api_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_v1_agent_proto = out.File
	file_api_proto_agent_v1_agent_proto_goTypes = nil
	file_api_proto_agent_v1_agent_proto_depIdxs = nil
}
