// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pkg/backuppb/v1/backup.proto

package backuppbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackupService_GetChallenge_FullMethodName    = "/backup.v1.BackupService/GetChallenge"
	BackupService_GetGlobalConfig_FullMethodName = "/backup.v1.BackupService/GetGlobalConfig"
	BackupService_PushBackup_FullMethodName      = "/backup.v1.BackupService/PushBackup"
	BackupService_GetQuotaUsage_FullMethodName   = "/backup.v1.BackupService/GetQuotaUsage"
	BackupService_PullRestore_FullMethodName     = "/backup.v1.BackupService/PullRestore"
)

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupServiceClient interface {
	GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*Challenge, error)
	GetGlobalConfig(ctx context.Context, in *GetGlobalConfigRequest, opts ...grpc.CallOption) (*GlobalConfig, error)
	PushBackup(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BackupBatch, BatchAck], error)
	GetQuotaUsage(ctx context.Context, in *GetQuotaUsageRequest, opts ...grpc.CallOption) (*QuotaUsage, error)
	PullRestore(ctx context.Context, in *PullRestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RestoreBatch], error)
}

type backupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupServiceClient(cc grpc.ClientConnInterface) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*Challenge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Challenge)
	err := c.cc.Invoke(ctx, BackupService_GetChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) GetGlobalConfig(ctx context.Context, in *GetGlobalConfigRequest, opts ...grpc.CallOption) (*GlobalConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalConfig)
	err := c.cc.Invoke(ctx, BackupService_GetGlobalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) PushBackup(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BackupBatch, BatchAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackupService_ServiceDesc.Streams[0], BackupService_PushBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupBatch, BatchAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_PushBackupClient = grpc.BidiStreamingClient[BackupBatch, BatchAck]

func (c *backupServiceClient) GetQuotaUsage(ctx context.Context, in *GetQuotaUsageRequest, opts ...grpc.CallOption) (*QuotaUsage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaUsage)
	err := c.cc.Invoke(ctx, BackupService_GetQuotaUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) PullRestore(ctx context.Context, in *PullRestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RestoreBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackupService_ServiceDesc.Streams[1], BackupService_PullRestore_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullRestoreRequest, RestoreBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_PullRestoreClient = grpc.ServerStreamingClient[RestoreBatch]

// BackupServiceServer is the server API for BackupService service.
// All implementations must embed UnimplementedBackupServiceServer
// for forward compatibility.
type BackupServiceServer interface {
	GetChallenge(context.Context, *GetChallengeRequest) (*Challenge, error)
	GetGlobalConfig(context.Context, *GetGlobalConfigRequest) (*GlobalConfig, error)
	PushBackup(grpc.BidiStreamingServer[BackupBatch, BatchAck]) error
	GetQuotaUsage(context.Context, *GetQuotaUsageRequest) (*QuotaUsage, error)
	PullRestore(*PullRestoreRequest, grpc.ServerStreamingServer[RestoreBatch]) error
	mustEmbedUnimplementedBackupServiceServer()
}

// UnimplementedBackupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServiceServer struct{}

func (UnimplementedBackupServiceServer) GetChallenge(context.Context, *GetChallengeRequest) (*Challenge, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallenge not implemented")
}
func (UnimplementedBackupServiceServer) GetGlobalConfig(context.Context, *GetGlobalConfigRequest) (*GlobalConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalConfig not implemented")
}
func (UnimplementedBackupServiceServer) PushBackup(grpc.BidiStreamingServer[BackupBatch, BatchAck]) error {
	return status.Error(codes.Unimplemented, "method PushBackup not implemented")
}
func (UnimplementedBackupServiceServer) GetQuotaUsage(context.Context, *GetQuotaUsageRequest) (*QuotaUsage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuotaUsage not implemented")
}
func (UnimplementedBackupServiceServer) PullRestore(*PullRestoreRequest, grpc.ServerStreamingServer[RestoreBatch]) error {
	return status.Error(codes.Unimplemented, "method PullRestore not implemented")
}
func (UnimplementedBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {}
func (UnimplementedBackupServiceServer) testEmbeddedByValue()                       {}

// UnsafeBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServiceServer will
// result in compilation errors.
type UnsafeBackupServiceServer interface {
	mustEmbedUnimplementedBackupServiceServer()
}

func RegisterBackupServiceServer(s grpc.ServiceRegistrar, srv BackupServiceServer) {
	// If the following call panics, it indicates UnimplementedBackupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupService_ServiceDesc, srv)
}

func _BackupService_GetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_GetChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetChallenge(ctx, req.(*GetChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_GetGlobalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetGlobalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_GetGlobalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetGlobalConfig(ctx, req.(*GetGlobalConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_PushBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupServiceServer).PushBackup(&grpc.GenericServerStream[BackupBatch, BatchAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_PushBackupServer = grpc.BidiStreamingServer[BackupBatch, BatchAck]

func _BackupService_GetQuotaUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuotaUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetQuotaUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_GetQuotaUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetQuotaUsage(ctx, req.(*GetQuotaUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_PullRestore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRestoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackupServiceServer).PullRestore(m, &grpc.GenericServerStream[PullRestoreRequest, RestoreBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackupService_PullRestoreServer = grpc.ServerStreamingServer[RestoreBatch]

// BackupService_ServiceDesc is the grpc.ServiceDesc for BackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backup.v1.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChallenge",
			Handler:    _BackupService_GetChallenge_Handler,
		},
		{
			MethodName: "GetGlobalConfig",
			Handler:    _BackupService_GetGlobalConfig_Handler,
		},
		{
			MethodName: "GetQuotaUsage",
			Handler:    _BackupService_GetQuotaUsage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushBackup",
			Handler:       _BackupService_PushBackup_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PullRestore",
			Handler:       _BackupService_PullRestore_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/backuppb/v1/backup.proto",
}
