// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/backuppb/v1/backup.proto

package backuppbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRequest) Reset() {
	*x = GetChallengeRequest{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRequest) ProtoMessage() {}

func (x *GetChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{0}
}

type Challenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix timestamp, now+5min
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *Challenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Challenge) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetGlobalConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalConfigRequest) Reset() {
	*x = GetGlobalConfigRequest{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalConfigRequest) ProtoMessage() {}

func (x *GetGlobalConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalConfigRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *GetGlobalConfigRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GlobalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalRules   []*GlobalRule          `protobuf:"bytes,1,rep,name=global_rules,json=globalRules,proto3" json:"global_rules,omitempty"`
	UserPolicy    *UserPolicy            `protobuf:"bytes,2,opt,name=user_policy,json=userPolicy,proto3" json:"user_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalConfig) GetGlobalRules() []*GlobalRule {
	if x != nil {
		return x.GlobalRules
	}
	return nil
}

func (x *GlobalConfig) GetUserPolicy() *UserPolicy {
	if x != nil {
		return x.UserPolicy
	}
	return nil
}

type GlobalRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalRule) Reset() {
	*x = GlobalRule{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalRule) ProtoMessage() {}

func (x *GlobalRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalRule.ProtoReflect.Descriptor instead.
func (*GlobalRule) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GlobalRule) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *GlobalRule) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type UserPolicy struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	DefaultSchedule  string                   `protobuf:"bytes,1,opt,name=default_schedule,json=defaultSchedule,proto3" json:"default_schedule,omitempty"`
	DefaultQuotaGb   int64                    `protobuf:"varint,2,opt,name=default_quota_gb,json=defaultQuotaGb,proto3" json:"default_quota_gb,omitempty"`
	PerUserOverrides map[string]*UserOverride `protobuf:"bytes,3,rep,name=per_user_overrides,json=perUserOverrides,proto3" json:"per_user_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserPolicy) Reset() {
	*x = UserPolicy{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPolicy) ProtoMessage() {}

func (x *UserPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPolicy.ProtoReflect.Descriptor instead.
func (*UserPolicy) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *UserPolicy) GetDefaultSchedule() string {
	if x != nil {
		return x.DefaultSchedule
	}
	return ""
}

func (x *UserPolicy) GetDefaultQuotaGb() int64 {
	if x != nil {
		return x.DefaultQuotaGb
	}
	return 0
}

func (x *UserPolicy) GetPerUserOverrides() map[string]*UserOverride {
	if x != nil {
		return x.PerUserOverrides
	}
	return nil
}

type UserOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuotaGb       int64                  `protobuf:"varint,1,opt,name=quota_gb,json=quotaGb,proto3" json:"quota_gb,omitempty"`
	Schedule      string                 `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"` // optional override; empty means use default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOverride) Reset() {
	*x = UserOverride{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOverride) ProtoMessage() {}

func (x *UserOverride) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOverride.ProtoReflect.Descriptor instead.
func (*UserOverride) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *UserOverride) GetQuotaGb() int64 {
	if x != nil {
		return x.QuotaGb
	}
	return 0
}

func (x *UserOverride) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

type BackupBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                 // which user this batch belongs to
	RuleType      string                 `protobuf:"bytes,3,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"` // "user" or "machine"
	Files         []*FileEntry           `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // SSH signature: nonce || "PushBackup" || sha256(payload)
	Nonce         []byte                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupBatch) Reset() {
	*x = BackupBatch{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupBatch) ProtoMessage() {}

func (x *BackupBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupBatch.ProtoReflect.Descriptor instead.
func (*BackupBatch) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{7}
}

func (x *BackupBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BackupBatch) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BackupBatch) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *BackupBatch) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BackupBatch) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BackupBatch) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`        // relative path within the backup root
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`  // file contents
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`       // file mode bits
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"` // true = file was deleted, remove on server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{8}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileEntry) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type BatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "OK" or "ERROR"
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`   // error detail if status == "ERROR"
	WrittenBytes  int64                  `protobuf:"varint,4,opt,name=written_bytes,json=writtenBytes,proto3" json:"written_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{9}
}

func (x *BatchAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BatchAck) GetWrittenBytes() int64 {
	if x != nil {
		return x.WrittenBytes
	}
	return 0
}

type GetQuotaUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // SSH signature: nonce || "GetQuotaUsage" || sha256(payload)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuotaUsageRequest) Reset() {
	*x = GetQuotaUsageRequest{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotaUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaUsageRequest) ProtoMessage() {}

func (x *GetQuotaUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaUsageRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaUsageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuotaUsageRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetQuotaUsageRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *GetQuotaUsageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type QuotaUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     int64                  `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	QuotaBytes    int64                  `protobuf:"varint,2,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	Dataset       string                 `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaUsage) Reset() {
	*x = QuotaUsage{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaUsage) ProtoMessage() {}

func (x *QuotaUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaUsage.ProtoReflect.Descriptor instead.
func (*QuotaUsage) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{11}
}

func (x *QuotaUsage) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *QuotaUsage) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *QuotaUsage) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

type PullRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // SSH signature: nonce || "PullRestore" || sha256(payload)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRestoreRequest) Reset() {
	*x = PullRestoreRequest{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRestoreRequest) ProtoMessage() {}

func (x *PullRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRestoreRequest.ProtoReflect.Descriptor instead.
func (*PullRestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{12}
}

func (x *PullRestoreRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PullRestoreRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PullRestoreRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RestoreBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Files         []*FileEntry           `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBatch) Reset() {
	*x = RestoreBatch{}
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBatch) ProtoMessage() {}

func (x *RestoreBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_backuppb_v1_backup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBatch.ProtoReflect.Descriptor instead.
func (*RestoreBatch) Descriptor() ([]byte, []int) {
	return file_pkg_backuppb_v1_backup_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *RestoreBatch) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *RestoreBatch) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

var File_pkg_backuppb_v1_backup_proto protoreflect.FileDescriptor

const file_pkg_backuppb_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/backuppb/v1/backup.proto\x12\tbackup.v1\"\x15\n" +
	"\x13GetChallengeRequest\"@\n" +
	"\tChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"4\n" +
	"\x16GetGlobalConfigRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x80\x01\n" +
	"\fGlobalConfig\x128\n" +
	"\fglobal_rules\x18\x01 \x03(\v2\x15.backup.v1.GlobalRuleR\vglobalRules\x126\n" +
	"\vuser_policy\x18\x02 \x01(\v2\x15.backup.v1.UserPolicyR\n" +
	"userPolicy\"P\n" +
	"\n" +
	"GlobalRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\"\x9a\x02\n" +
	"\n" +
	"UserPolicy\x12)\n" +
	"\x10default_schedule\x18\x01 \x01(\tR\x0fdefaultSchedule\x12(\n" +
	"\x10default_quota_gb\x18\x02 \x01(\x03R\x0edefaultQuotaGb\x12Y\n" +
	"\x12per_user_overrides\x18\x03 \x03(\v2+.backup.v1.UserPolicy.PerUserOverridesEntryR\x10perUserOverrides\x1a\\\n" +
	"\x15PerUserOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.backup.v1.UserOverrideR\x05value:\x028\x01\"E\n" +
	"\fUserOverride\x12\x19\n" +
	"\bquota_gb\x18\x01 \x01(\x03R\aquotaGb\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\"\xc1\x01\n" +
	"\vBackupBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\trule_type\x18\x03 \x01(\tR\bruleType\x12*\n" +
	"\x05files\x18\x04 \x03(\v2\x14.backup.v1.FileEntryR\x05files\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\fR\x05nonce\"g\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\"x\n" +
	"\bBatchAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12#\n" +
	"\rwritten_bytes\x18\x04 \x01(\x03R\fwrittenBytes\"f\n" +
	"\x14GetQuotaUsageRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"f\n" +
	"\n" +
	"QuotaUsage\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vquota_bytes\x18\x02 \x01(\x03R\n" +
	"quotaBytes\x12\x18\n" +
	"\adataset\x18\x03 \x01(\tR\adataset\"d\n" +
	"\x12PullRestoreRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"n\n" +
	"\fRestoreBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12*\n" +
	"\x05files\x18\x02 \x03(\v2\x14.backup.v1.FileEntryR\x05files\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast2\xf5\x02\n" +
	"\rBackupService\x12D\n" +
	"\fGetChallenge\x12\x1e.backup.v1.GetChallengeRequest\x1a\x14.backup.v1.Challenge\x12M\n" +
	"\x0fGetGlobalConfig\x12!.backup.v1.GetGlobalConfigRequest\x1a\x17.backup.v1.GlobalConfig\x12=\n" +
	"\n" +
	"PushBackup\x12\x16.backup.v1.BackupBatch\x1a\x13.backup.v1.BatchAck(\x010\x01\x12G\n" +
	"\rGetQuotaUsage\x12\x1f.backup.v1.GetQuotaUsageRequest\x1a\x15.backup.v1.QuotaUsage\x12G\n" +
	"\vPullRestore\x12\x1d.backup.v1.PullRestoreRequest\x1a\x17.backup.v1.RestoreBatch0\x01B9Z7github.com/example/datavault/pkg/backuppb/v1;backuppbv1b\x06proto3"

var (
	file_pkg_backuppb_v1_backup_proto_rawDescOnce sync.Once
	file_pkg_backuppb_v1_backup_proto_rawDescData []byte
)

func file_pkg_backuppb_v1_backup_proto_rawDescGZIP() []byte {
	file_pkg_backuppb_v1_backup_proto_rawDescOnce.Do(func() {
		file_pkg_backuppb_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_backuppb_v1_backup_proto_rawDesc), len(file_pkg_backuppb_v1_backup_proto_rawDesc)))
	})
	return file_pkg_backuppb_v1_backup_proto_rawDescData
}

var file_pkg_backuppb_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_backuppb_v1_backup_proto_goTypes = []any{
	(*GetChallengeRequest)(nil),    // 0: backup.v1.GetChallengeRequest
	(*Challenge)(nil),              // 1: backup.v1.Challenge
	(*GetGlobalConfigRequest)(nil), // 2: backup.v1.GetGlobalConfigRequest
	(*GlobalConfig)(nil),           // 3: backup.v1.GlobalConfig
	(*GlobalRule)(nil),             // 4: backup.v1.GlobalRule
	(*UserPolicy)(nil),             // 5: backup.v1.UserPolicy
	(*UserOverride)(nil),           // 6: backup.v1.UserOverride
	(*BackupBatch)(nil),            // 7: backup.v1.BackupBatch
	(*FileEntry)(nil),              // 8: backup.v1.FileEntry
	(*BatchAck)(nil),               // 9: backup.v1.BatchAck
	(*GetQuotaUsageRequest)(nil),   // 10: backup.v1.GetQuotaUsageRequest
	(*QuotaUsage)(nil),             // 11: backup.v1.QuotaUsage
	(*PullRestoreRequest)(nil),     // 12: backup.v1.PullRestoreRequest
	(*RestoreBatch)(nil),           // 13: backup.v1.RestoreBatch
	nil,                            // 14: backup.v1.UserPolicy.PerUserOverridesEntry
}
var file_pkg_backuppb_v1_backup_proto_depIdxs = []int32{
	4,  // 0: backup.v1.GlobalConfig.global_rules:type_name -> backup.v1.GlobalRule
	5,  // 1: backup.v1.GlobalConfig.user_policy:type_name -> backup.v1.UserPolicy
	14, // 2: backup.v1.UserPolicy.per_user_overrides:type_name -> backup.v1.UserPolicy.PerUserOverridesEntry
	8,  // 3: backup.v1.BackupBatch.files:type_name -> backup.v1.FileEntry
	8,  // 4: backup.v1.RestoreBatch.files:type_name -> backup.v1.FileEntry
	6,  // 5: backup.v1.UserPolicy.PerUserOverridesEntry.value:type_name -> backup.v1.UserOverride
	0,  // 6: backup.v1.BackupService.GetChallenge:input_type -> backup.v1.GetChallengeRequest
	2,  // 7: backup.v1.BackupService.GetGlobalConfig:input_type -> backup.v1.GetGlobalConfigRequest
	7,  // 8: backup.v1.BackupService.PushBackup:input_type -> backup.v1.BackupBatch
	10, // 9: backup.v1.BackupService.GetQuotaUsage:input_type -> backup.v1.GetQuotaUsageRequest
	12, // 10: backup.v1.BackupService.PullRestore:input_type -> backup.v1.PullRestoreRequest
	1,  // 11: backup.v1.BackupService.GetChallenge:output_type -> backup.v1.Challenge
	3,  // 12: backup.v1.BackupService.GetGlobalConfig:output_type -> backup.v1.GlobalConfig
	9,  // 13: backup.v1.BackupService.PushBackup:output_type -> backup.v1.BatchAck
	11, // 14: backup.v1.BackupService.GetQuotaUsage:output_type -> backup.v1.QuotaUsage
	13, // 15: backup.v1.BackupService.PullRestore:output_type -> backup.v1.RestoreBatch
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_backuppb_v1_backup_proto_init() }
func file_pkg_backuppb_v1_backup_proto_init() {
	if File_pkg_backuppb_v1_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_backuppb_v1_backup_proto_rawDesc), len(file_pkg_backuppb_v1_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_backuppb_v1_backup_proto_goTypes,
		DependencyIndexes: file_pkg_backuppb_v1_backup_proto_depIdxs,
		MessageInfos:      file_pkg_backuppb_v1_backup_proto_msgTypes,
	}.Build()
	File_pkg_backuppb_v1_backup_proto = out.File
	file_pkg_backuppb_v1_backup_proto_goTypes = nil
	file_pkg_backuppb_v1_backup_proto_depIdxs = nil
}
